# Generated by Django 5.0.1 on 2024-03-22 16:46

import django.contrib.postgres.fields
import django.db.models.deletion
import menuitem_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menuitem_app.menuitemextra')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=menuitem_app.models.menuitem_image_path)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, null=True, size=None)),
                ('sizes_and_prices', models.JSONField(default=list)),
                ('extras', models.ManyToManyField(blank=True, to='menuitem_app.menuitemextra')),
                ('types', models.ManyToManyField(blank=True, to='menuitem_app.menuitemtype')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menuitem_app.menuitemtype')),
            ],
        ),
    ]
